source 'https://rubygems.org'
ruby '~> 3.2'

gem 'rails', '~> 7.0.8'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'devise', '~> 4.9'
gem 'jwt', '~> 3.1'
gem 'bcrypt', '~> 3.1.20'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.0'
gem 'connection_pool', '~> 2.4'
gem 'kaminari'
gem 'active_model_serializers', '~> 0.10.15'
gem 'rack-cors', '~> 2.0'
gem 'paper_trail', '~> 16.0'
gem 'dotenv-rails', '~> 3.1'
gem 'jbuilder'
gem 'rack-attack', '~> 6.7'
gem 'ruby-openai', '~> 7.0'
gem 'sentry-ruby', '~> 5.0'
gem 'sentry-rails', '~> 5.0'
gem 'httparty', '~> 0.21'
gem 'aws-sdk-s3', '~> 1.0'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.2'
end

group :development do
  gem 'web-console', '~> 4.2'
  gem 'bullet', '~> 7.1'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
end
